# Generated by Django 4.1.3 on 2022-12-12 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("resenias", "0002_resenia_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="resenia",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
