# Generated by Django 4.1.4 on 2022-12-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='gratuito',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
